# Generated by Django 5.1.5 on 2025-01-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='', verbose_name='Постер'),
        ),
    ]
